### ISSUE TITLE
Get Involved Expands Not Working

### ISSUE THREAD

**Issue by JackThorp** [dellsystem/the-world-transformed#39]
<img width="1280" alt="screen shot 2018-09-04 at 11 35 52" src="https://user-images.githubusercontent.com/4509322/45026694-ffbb7d00-b036-11e8-8b1f-b9f7ed16953c.png">

**Comment by dellsystem** [comment]
ahh crap it's probably a jquery version mismatch - one of the plugins we're using expect an older version, whereas semantic must expect a newer version. will look into it
