### ISSUE TITLE
Fix triangle background image on mobile/tablet

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/the-world-transformed#6]
Looks weird. resize so that it covers more of the background behind the text?

**Comment by JackThorp** [comment]
Yeah. This and mobile menu are maybe most important as they affect usability / readability. All body text should be on white background. It's okay for parts of headings to overlap with grid background however.

**Comment by dellsystem** [comment]
this is tricky because dimensions will be somewhat dynamic on mobile. for now, just gonna set white backgrounds for these sections to ensure readability on mobile/tabket
